version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    command: bash -c 'sleep 5 && npm start'

  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config: